apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-limit-range
spec:
  limits:
  - default:
      cpu: 1
    defaultRequest:
      cpu: 0.5
    type: Container


#使用LimitRange对象的配置文件，指定默认的CPU请求和一个默认的CPU限额
#在命名空间运行的每一个容器必须含有它自己的CPU限额
#在命名空间所有容器使用CPU总量不能超出指定的限额