apiVersion: v1
kind: Pod
metadata:
   name: constraints-mem-demo
spec:
  containers:
  - name: constraints-mem-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "800Mi"
      requests:
        memory: "600Mi"

#在指定最大 1g,最小500m得namespace 下创建pod,所创建得pod必须符合该条件才允许创建，否则创建失败