apiVersion: v1
kind: Pod
metadata:
  name: server
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /mypath
      name: git-volume
  volumes:
  - name: git-volume
    gitRepo:
      repository: "https://github.com/AiLoi/MyBlog.git"
      revision: "a951a977b0b846fdba9e9eb9e11f87bcfe4cccac"