apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    # This GCE PD must already exist.
    gcePersistentDisk:
      pdName: my-data-disk
      fsType: ext4

#gcePersistentDisk 可以挂在GCE上的永久磁盘到容器，需要kubernetes运行在GCE的VM中
#Pod删除时，gcePersistentDisk被删除，但Persistent Disk的内容仍然存在。

#使用GCE PD与pod之前，需要创建它
#gcloud compute disks create --size=500GB --zone=us-central1-a my-data-disk
