apiVersion: v1
kind: Pod
metadata:
  name: test-portworx-volume-pod
spec:
  containers:
    - name: test-container
      image: gc.io/google_container/test-webserver
      volumeMounts:
        - mountPath: /mnt
          name: pxvol
  volumes:
    - name: pxvol
      portworxVolume:
        volumeID: pxvol
        fsType: <fs-type>

# Portworx 能把服务器容器进行蓄积，将服务器或者云实例变成一个聚合的高可用的计算和存储节点
