apiVersion: v1
kind: Pod
metadata:
  name: volume-test
spec:
  containers:
    - name: container-test
      image: busybox
      volumeMounts:
        - mountPath: /projected=volume
          name: all-in-one
          readOnly: true
  volumes:
    - name: all-in-one
      projected:
        sources:
          - secret:
              name: mysecret
              items:
                - key: username
                  path: my-group/my-username
          - downwardAPI:
              items:
                - path: labels
                  fieldRef:
                    fieldPath: metadata.labels
                - path: cpu_limit
                  resourceFieldRef:
                    resource: limit.cpu
                    containerName: container-test
          - configMap:
              name: myconfigmap
              items:
                - key: config
                  path: my-group/my-config

#Projected Volume将多个volume源映射到同一个目录
#目前支持：
#- secret
#- downwardAPI
#- configMap