apiVersion: v1
kind: Pod
metadata:
  name: pod-0
spec:
  containers:
    - name: pod-0
      image: gcr.io/google_containers/test-webserver
      volumeMounts:
        - mountPath: /test-pd
          name: vol-0
  volumes:
    - name: vol-0
      scaleIO:
        gateway: https://localhost:443/api
        secretRef:
          name: sio-secret
        system: scaleio
        fsType: xfs


# scaleio 是一种基于软件的存储平台，可以使用现有硬件来创建可以扩展共享网络存储的集群
# scaleio 卷插件允许部署的pod 访问现有的scaleio卷