apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-scaler
spec:
  maxReplicas: 10
  scaleTargetRef:
    kind: ReplicaSet
    name: frontend
  minReplicas: 3
  targetCPUUtilizationPercentage: 50