apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
              {
                  "name": "init-myservice",
                  "image": "busybox",
                  "command": ["sh", "-c", "until nslookup myservice; do echo waiting for myservice; sleep 2; done;"]
              },
              {
                  "name": "init-mydb",
                  "image": "busybox",
                  "command": ["sh", "-c", "until nslookup mydb; do echo waiting for mydb; sleep 2; done;"]
              }
          ]'
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ['sh', '-c', 'echo The app is running! && sleep 3600']

#这是一个具有两个init容器的简单Pod。第一个等待myservice启动，第二个等待mydb启动，一旦这两个Service都启动完成，Pod将开始启动
